### PR TITLE
Fix actions

### PR DESCRIPTION
**Pull request by Persson-dev**
Changed default version of flutter to "stable"

### CODE REVIEW

**Review by hatch01 — APPROVED** [review]

**Comment by Persson-dev** [comment]
Do I need to add more things because of melos or is it good ?

**Comment by hatch01** [comment]
> Do I need to add more things because of melos or is it good ?

No melos is only needed in the development process but not used in release builds.

**Comment by Persson-dev** [comment]
Should I also add checks when things are pushed to main/dev (without a PR) ?

**Comment by hatch01** [comment]
> Should I also add checks when things are pushed to main/dev (without a PR) ?

In dev no because it is in development and often needs some local library binding to build. In main why not, but there is a rule which prevents pushing to main without PR, so I think it's not useful.

**Comment by hatch01** [comment]
for the android fail, I had the bug often (and forgot how to fix it. maybe juste flutter clean and then flutter build could do the trick).

**Pull request merged**
